name: Build and deploy to EC2

on:
    push:
        branches:
            -   master
    
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out repo
                uses: actions/checkout@v2

            -   name: Log in to Docker Hub
                uses: docker/login-action@v1
                with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
          
            -   name: Build and Push Docker image
                uses: docker/build-push-action@v2
                with:
                  context: .
                  file: ./docker/Dockerfile.userApp
                  push: true
                  tags: adheil/myciimage:latest
          
            -   name: Verify Pushed Image
                run: docker pull adheil/myciimage:latest

            -   name: SSH into EC2 instance and deploy
                uses: appleboy/ssh-action@v.0.1.3
                with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.MY_EC2_SSH_KEY }}
                  script: |
                    sudo docker pull adheil/myciimage:latest
                    sudo docker stop my-node-app || true
                    sudo docker rm my-node-app || true
                    sudo docker run -d -p 3000:3000 --name my-user-app adheil/myciimage:latest
              